import React from 'react'
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom'
import Home from './pages/Home'
import Hampers from './pages/Hampers'
import Corporate from './pages/Corporate'
import About from './pages/About'
import Contact from './pages/Contact'
import Header from './components/Header'
import Footer from './components/Footer'
import WhatsAppFab from './components/WhatsAppFab'
export default function App(){ return (<Router><Header /><main className='pt-4'><Routes><Route path='/' element={<Home/>} /><Route path='/hampers' element={<Hampers/>} /><Route path='/corporate' element={<Corporate/>} /><Route path='/about' element={<About/>} /><Route path='/contact' element={<Contact/>} /></Routes></main><Footer /><WhatsAppFab /><div id='snow' className='snow'></div></Router>) }
